ALTER TABLE case_studies
ADD COLUMN IF NOT EXISTS the_context TEXT,
ADD COLUMN IF NOT EXISTS the_challenge TEXT,
ADD COLUMN IF NOT EXISTS the_approach TEXT,
ADD COLUMN IF NOT EXISTS the_impact TEXT,
ADD COLUMN IF NOT EXISTS impact_metric_1 TEXT,
ADD COLUMN IF NOT EXISTS impact_label_1 TEXT,
ADD COLUMN IF NOT EXISTS impact_metric_2 TEXT,
ADD COLUMN IF NOT EXISTS impact_label_2 TEXT,
ADD COLUMN IF NOT EXISTS live_site_link TEXT;
